apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: trafficsplits.split.smi-spec.io
spec:
  additionalPrinterColumns:
  - JSONPath: .spec.service
    description: The service
    name: Service
    type: string
  group: split.smi-spec.io
  names:
    kind: TrafficSplit
    listKind: TrafficSplitList
    plural: trafficsplits
    singular: trafficsplit
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
