name: IstioSM
services:
  istio:
    type: IstioMesh
    model: ISTIO
    namespace: istio-system
    version: 1.16.1 #will be filled dynamically in workflow
    settings:
      profile: demo
    traits:
      automaticSidecarInjection:
        namespaces:
          - default
  grafana:
    type: GrafanaIstioAddon
    model: ISTIO
    version: 1.16.1 #will be filled dynamically in workflow
    namespace: istio-system
    dependsOn:
      - istio
      - prometheus
  prometheus:
    type: PrometheusIstioAddon
    model: ISTIO
    version: 1.16.1 #will be filled dynamically in workflow
    namespace: istio-system
    dependsOn:
      - istio